name = "confire-platform-dev"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[vars]
PUBLIC_WORKER_URL = "https://api.dev.confire.dev"

# Production environment (confire.dev)
[env.production]
name = "confire-platform"

[env.production.vars]
PUBLIC_WORKER_URL = "https://api.confire.dev"
